"""
Scaffold Engine — generate Snowflake project scaffolds on demand.

Supports:
  pipeline-project  — Dynamic Tables Medallion Pipeline
  app-project       — Streamlit in Snowflake App
  cortex-project    — Cortex AI LLM Pipeline
  snowpark-project  — Snowpark Python UDF/UDTF
"""
import os
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt

console = Console()

TEMPLATES = {
    "pipeline-project": "Dynamic Tables Medallion Pipeline (Bronze/Silver/Gold)",
    "app-project":      "Streamlit in Snowflake Application",
    "cortex-project":   "Cortex AI Document Processing Pipeline",
    "snowpark-project": "Snowpark Python UDFs and Stored Procedures",
}


class ScaffoldEngine:

    def run(self, template: str | None = None) -> None:
        if not template:
            self._show_menu()
            return

        template = template.strip().lower()
        if template not in TEMPLATES:
            console.print(f"[red]Unknown template:[/] {template}")
            self._show_menu()
            return

        generator = getattr(self, f"_gen_{template.replace('-', '_')}", None)
        if generator:
            generator()
        else:
            console.print(f"[yellow]Template '{template}' is registered but not yet generated. Coming soon.[/]")

    def _show_menu(self) -> None:
        rows = "\n".join(
            f"  [bold yellow]/scaffold {k:<20}[/] [dim]{v}[/]"
            for k, v in TEMPLATES.items()
        )
        console.print(Panel(rows, title="[bold white]Available Scaffolds[/]", border_style="cyan", padding=(0, 2)))

    def _gen_pipeline_project(self) -> None:
        project_name = Prompt.ask("[cyan]Project name[/]", default="medallion_pipeline")
        database = Prompt.ask("[cyan]Target Database[/]", default="PROD_DB")
        schema = Prompt.ask("[cyan]Target Schema[/]", default="PIPELINE")
        warehouse = Prompt.ask("[cyan]Compute Warehouse[/]", default="TRANSFORM_WH")

        root = Path.cwd() / project_name
        root.mkdir(exist_ok=True)
        (root / "src").mkdir(exist_ok=True)

        (root / "src" / "01_bronze.sql").write_text(f'''\
-- SnowNinja — Medallion Architecture
-- Project: {project_name}

USE DATABASE {database};
USE SCHEMA {schema};

CREATE OR REPLACE DYNAMIC TABLE bronze_events
  TARGET_LAG = '10 minutes'
  WAREHOUSE = {warehouse}
  AS
    SELECT
      $1:id::string AS event_id,
      $1:timestamp::timestamp AS event_time,
      $1:payload::variant AS raw_payload,
      metadata$filename AS source_file
    FROM @raw_stage/events/;
''')

        (root / "src" / "02_silver.sql").write_text(f'''\
USE DATABASE {database};
USE SCHEMA {schema};

CREATE OR REPLACE DYNAMIC TABLE silver_events
  TARGET_LAG = '10 minutes'
  WAREHOUSE = {warehouse}
  AS
    SELECT
      event_id,
      event_time,
      raw_payload:user_id::string AS user_id,
      raw_payload:action::string AS action,
      raw_payload:amount::number(10,2) AS amount
    FROM bronze_events
    WHERE raw_payload IS NOT NULL;
''')

        (root / "README.md").write_text(f"# {project_name}\n\nGenerated by SnowNinja CLI.\n\nDeploy with Snowflake CLI: `snow sql -f src/01_bronze.sql`\n")

        console.print(Panel(
            f"[green]✓[/] Scaffolded [bold]{project_name}[/] at [white]{root}[/]\n\n"
            f"  [dim]Next steps:[/]\n"
            f"  1. [yellow]cd {project_name}[/]\n"
            f"  2. [yellow]snow sql -f src/01_bronze.sql[/]",
            title="Scaffold Complete",
            border_style="green",
        ))

    def _gen_app_project(self) -> None:
        project_name = Prompt.ask("[cyan]Project name[/]", default="my_streamlit_app")
        database = Prompt.ask("[cyan]Target Database[/]", default="APPS_DB")
        schema = Prompt.ask("[cyan]Target Schema[/]", default="PUBLIC")

        root = Path.cwd() / project_name
        root.mkdir(exist_ok=True)

        (root / "app.py").write_text(f'''\
# SnowNinja — Streamlit in Snowflake
# Project: {project_name}

import streamlit as st
from snowflake.snowpark.context import get_active_session

st.title("{project_name}")

session = get_active_session()
df = session.sql("SELECT current_user(), current_role(), current_warehouse()").to_pandas()

st.write("### Current Context")
st.dataframe(df)

st.write("Ready to build your native app!")
''')

        (root / "snowflake.yml").write_text(f'''\
definition_version: 1
streamlit:
  name: {project_name}
  stage: app_stage
  query_warehouse: APP_WH
  main_file: "app.py"
  database: {database}
  schema: {schema}
''')

        (root / "README.md").write_text(f"# {project_name}\n\nGenerated by SnowNinja CLI.\n\nDeploy: `snow streamlit deploy`\n")

        console.print(Panel(f"[green]✓[/] App scaffold at [white]{root}[/]", title="Scaffold Complete", border_style="green"))

    def _gen_cortex_project(self) -> None:
        project_name = Prompt.ask("[cyan]Project name[/]", default="cortex_processor")
        database = Prompt.ask("[cyan]Target Database[/]", default="AI_DB")

        root = Path.cwd() / project_name
        root.mkdir(exist_ok=True)

        (root / "process_docs.sql").write_text(f'''\
-- SnowNinja — Cortex AI Pipeline
-- Project: {project_name}

USE DATABASE {database};

-- 1. Create source table
CREATE OR REPLACE TABLE customer_feedback (
    id INT AUTOINCREMENT,
    raw_text VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Process with Cortex
CREATE OR REPLACE VIEW analyzed_feedback AS
SELECT
    id,
    raw_text,
    SNOWFLAKE.CORTEX.SENTIMENT(raw_text) AS sentiment_score,
    SNOWFLAKE.CORTEX.SUMMARIZE(raw_text) AS summary,
    SNOWFLAKE.CORTEX.CLASSIFY(
        raw_text, 
        ['Bug Report', 'Feature Request', 'Praise', 'Complaint']
    ) AS category
FROM customer_feedback;
''')

        (root / "README.md").write_text(f"# {project_name}\n\nGenerated by SnowNinja CLI.\n")
        console.print(Panel(f"[green]✓[/] Cortex pipeline scaffold at [white]{root}[/]", title="Scaffold Complete", border_style="green"))

    def _gen_snowpark_project(self) -> None:
        project_name = Prompt.ask("[cyan]Project name[/]", default="snowpark_udfs")
        root = Path.cwd() / project_name
        root.mkdir(exist_ok=True)
        (root / "src").mkdir(exist_ok=True)

        (root / "src" / "functions.py").write_text(f'''\
import _snowflake

def clean_text(text: str) -> str:
    """A simple Python UDF for text cleaning."""
    if not text:
        return ""
    return text.strip().lower()
''')

        (root / "snowflake.yml").write_text(f'''\
definition_version: 1
snowpark:
  project_name: {project_name}
  functions:
    - name: clean_text
      handler: src.functions.clean_text
      returns: string
      signature:
        - name: text
          type: string
''')
        (root / "README.md").write_text(f"# {project_name}\n\nGenerated by SnowNinja CLI.\n\nDeploy: `snow snowpark build && snow snowpark deploy`\n")
        console.print(Panel(f"[green]✓[/] Snowpark scaffold at [white]{root}[/]", title="Scaffold Complete", border_style="green"))

